######################################################################
# Automatically generated by qmake (2.01a) ? 8? 7 15:16:50 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += ../../../c/qt4/custommainwindow
INCLUDEPATH += .

# Input
HEADERS += custommainwindow.hpp
SOURCES += custommainwindow.cpp main.cpp
