######################################################################
# Automatically generated by qmake (2.01a) ? 8? 10 22:58:21 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += ../../../c/qt4/test_japanese
INCLUDEPATH += .

# Input
SOURCES += main_japanese.cpp
