######################################################################
# Automatically generated by qmake (2.01a) ? 8? 7 14:02:12 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += ../../../c/qt4/hello
INCLUDEPATH += .

# Input
SOURCES += qthello.cpp
