######################################################################
# Automatically generated by qmake (2.01a) ? 10? 30 00:22:11 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += ../../../c/qt4/KsTRS
INCLUDEPATH += .

# Input
HEADERS += CustomWidget.hpp MainWindow.hpp
SOURCES += CustomWidget.cpp main.cpp MainWindow.cpp
