######################################################################
# Automatically generated by qmake (2.01a) ? 10? 29 21:54:01 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += ../../../c/qt4/GUI_SOM
INCLUDEPATH += .

# Input
HEADERS += CustomWidget.hpp \
           MainWindow.hpp \
           som.hpp \
           ../../../c/rnd_shuffle.h \
           ../../../c/data.h
SOURCES += CustomWidget.cpp main.cpp MainWindow.cpp
